# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go
services:
  - docker


go:
  - 1.12.x

git:
  depth: 1


install: true

before_install:
  - docker pull redis

notifications:
  email: false

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - make unit-test
  - make integration-test
  - make clean
