apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: node-aggregation
spec:
  selector:
    matchLabels:
      app: node-aggregation
  replicas: 2
  template:
    metadata:
      labels:
        app: node-aggregation
    spec:
      containers:
        - name: node-aggregation
          image: node-aggregation:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 15
